// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpt1_bQgktyFSJsAz5x53t8Gui6lQjNRM',
    appId: '1:895774316068:web:d21c90020485ebec22eab1',
    messagingSenderId: '895774316068',
    projectId: 'playground-84249',
    authDomain: 'playground-84249.firebaseapp.com',
    databaseURL: 'https://playground-84249-default-rtdb.firebaseio.com',
    storageBucket: 'playground-84249.appspot.com',
    measurementId: 'G-SS6ZED71TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJSmoiFxBVw6KTPl_AvGKsKzt0kV_wzAk',
    appId: '1:895774316068:android:f72328136c68817522eab1',
    messagingSenderId: '895774316068',
    projectId: 'playground-84249',
    databaseURL: 'https://playground-84249-default-rtdb.firebaseio.com',
    storageBucket: 'playground-84249.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV22oCn6KMTpQ4EZw8Sshr3F2xHufnoHo',
    appId: '1:895774316068:ios:add0b16c6874e70422eab1',
    messagingSenderId: '895774316068',
    projectId: 'playground-84249',
    databaseURL: 'https://playground-84249-default-rtdb.firebaseio.com',
    storageBucket: 'playground-84249.appspot.com',
    androidClientId: '895774316068-n8a0k9rjef9drpp9c4p341gp4ggpmmqd.apps.googleusercontent.com',
    iosClientId: '895774316068-ecvh4qj8fqpo3ccip93c5ijesg46bbbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.playground',
  );
}
